- name: variables from files
  hosts: localhost # managing ansible server itself
  vars_files:
  - variables.yaml
  tasks: 
  - name: printing variables
    ansible.builtin.debug:
      msg: "We are learning {{NAME}}, Trainer is {{TRAINER}}, Duration is {{DURATION}}"