- name: variables at task level
  hosts: localhost
  # these variables of parent or play level
  vars:
  - money: "1,00,000 Rs"
    land: "1 acer"
  tasks:
  - name: inherit value from play
    ansible.builtin.debug:
      msg: "MONEY: {{money}}, LAND: {{land}}"
  - name: inherit values from play and override
    vars:
    - money: "2,00,000 Rs"
      houses: "3 Houses"
      ansible.builtin.debug:
        msg: "MONEY: {{money}}, LAND: {{land}}, houses: {{houses}}"
  