- name: testing variable precedence
  hosts: mongodb
  vars: 
    NAME: Sivakumar @ Play level
  vars_files:
  - variables.yaml
  vars_prompt:
  - name : NAME
    prompt: Please enter trainer name
    private: false
  tasks:
  - name: variables at task level
    vars:
      NAME: sivakumar @ task
    ansble.builtin.debug:
      msg: "Trainer Name is {{NAME}}"

# 1. Commandline variables
# 2. task level
# 3. vars_files
# 4. prompt
# 5. play
# 6. inventory
# 7. Roles ( we will discuss during roll discussion)