- name: creat users
  hosts: localhost
  tasks:
  - name: check roboshop user exist or not
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true
  - name: print the command output
    ansible.builtin.debug:
      msg: "command output is: {{output}}"
  - name: print exit status
    ansible.builtin.debug:
      msg: "{{output.rc}}"
  - name: create user roboshop
    ansible.builtin.user:
      name: roboshop
    when: output.rc != 0
    