- name: simple condition
  hosts: localhost
  vars: 
    NAME: DevOps
  tasks:
  - name: run this if name is devops
    ansible.builtin.debug:
      msg: "The name is {{NAME}}"
    when: NAME == "DevOps"
