- name: Install or uninstall softwares
  hosts: mongodb
  become: yes
  tasks:
  - name: printing application name
  ansible.builtin.debug:
    msg: "{{item.state}}" "{{item.name}}"
  - name: installing/removing application
    ansible.builtin.yum:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - {name: 'nginx', state: 'installed'}
    - {name: 'postfix', state: 'absent'}
    - {name: 'cyrus-sasl-plain', state: 'absent'}
    - {name: 'mailx', state: 'absent'}